In [2]:
import numpy as np

## リスト生成、スライス

In [8]:
# 1次元
a = np.array([1, 2, 3 ,4, 5, 6])
print("a     :", a)
print("a[2]  :", a[2])
print("a[2:4]:", a[2:4])
print("a[4:] :", a[4:])

# 2次元
b = np.array([[1, 2, 3 ,4, 5, 6],
              [1, 2, 3 ,4, 5, 6],
              [1, 2, 3 ,4, 5, 6]])
print("b:\n", b)
print("b[2]:\n", b[2])
print("b[0, 1:4]:\n", b[0, 1:4])
print("b[1:, 3:]:\n", b[1:, 3:])

a     : [1 2 3 4 5 6]
a[2]  : 3
a[2:4]: [3 4]
a[4:] : [5 6]
b:
 [[1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]]
b[2]:
 [1 2 3 4 5 6]
b[0, 1:4]:
 [2 3 4]
b[1:, 3:]:
 [[4 5 6]
 [4 5 6]]


## ndarryaの属性

In [9]:
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8]])
print(a.shape)
print(a.size)
print(a.ndim)
print(a.dtype)

(2, 4)
8
2
int32


## 配列の四則演算

In [5]:
a = np.array([3, 5, 7, 10, 12, 20])
b = np.array([2, 4, 2, 8, 20, 10])

# 加算
print(a + b)

# 減算
print(b - a)

# 乗算
print(a * b)

# 除算
print(a / b)

# 剰余
print(a % b)

[ 5  9  9 18 32 30]
[ -1  -1  -5  -2   8 -10]
[  6  20  14  80 240 200]
[1.5  1.25 3.5  1.25 0.6  2.  ]
[ 1  1  1  2 12  0]


## 合計、平均、最小、最大、分散、標準偏差

In [3]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("合計:", np.sum(a))
print("平均:", np.mean(a))
print("最小:", np.min(a))
print("最大:", np.max(a))
print("分散:", np.var(a))
print("標準偏差:", np.std(a))

合計: 55
平均: 5.5
最小: 1
最大: 10
分散: 8.25
標準偏差: 2.8722813232690143


## 乱数

In [10]:
# 一様分布
print(np.random.rand())
print(np.random.rand(2))
print(np.random.rand(2, 3))
print(np.random.randint(20))

0.4130990673349382
[0.96498919 0.31420507]
[[0.77691798 0.02422593 0.40687279]
 [0.27664747 0.36771185 0.49616832]]
6


In [11]:
# 正規分布
# 平均-1、標準偏差0.5の正規分布
print(np.random.normal(-1, 0.5))


-1.7016523903375513
